apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: Roboshop
  region: us-east-1

managedNodeGroups:
  - name: spot-ng-01
    instanceTypes:
      - t3.micro
    amiFamily: AmazonLinux2
    spot: true
    minSize: 1
    maxSize: 2
    desiredCapacity: 2